[2023-03-03 15:17:03 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5002']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f70f41651f0>
  on_reload: <function OnReload.on_reload at 0x7f70f4165310>
  when_ready: <function WhenReady.when_ready at 0x7f70f4165430>
  pre_fork: <function Prefork.pre_fork at 0x7f70f4165550>
  post_fork: <function Postfork.post_fork at 0x7f70f4165670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f70f4165790>
  worker_int: <function WorkerInt.worker_int at 0x7f70f41658b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f70f41659d0>
  pre_exec: <function PreExec.pre_exec at 0x7f70f4165af0>
  pre_request: <function PreRequest.pre_request at 0x7f70f4165c10>
  post_request: <function PostRequest.post_request at 0x7f70f4165ca0>
  child_exit: <function ChildExit.child_exit at 0x7f70f4165dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f70f4165ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f70f4171040>
  on_exit: <function OnExit.on_exit at 0x7f70f4171160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 15:17:03 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 15:17:03 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 15:17:03 +0000] [7] [INFO] Listening at: http://0.0.0.0:5002 (7)
[2023-03-03 15:17:03 +0000] [7] [INFO] Using worker: sync
[2023-03-03 15:17:03 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 15:17:03 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 15:17:03 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 15:17:03 +0000] [7] [DEBUG] 3 workers
[2023-03-03 15:17:06 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 15:17:06 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-03-03 15:17:06 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 15:17:06 +0000] [11] [INFO] Worker exiting (pid: 11)
[2023-03-03 15:17:06 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 15:17:06 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-03-03 15:17:07 +0000] [7] [WARNING] Worker with pid 10 was terminated due to signal 15
[2023-03-03 15:18:47 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5002']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f54e772b1f0>
  on_reload: <function OnReload.on_reload at 0x7f54e772b310>
  when_ready: <function WhenReady.when_ready at 0x7f54e772b430>
  pre_fork: <function Prefork.pre_fork at 0x7f54e772b550>
  post_fork: <function Postfork.post_fork at 0x7f54e772b670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f54e772b790>
  worker_int: <function WorkerInt.worker_int at 0x7f54e772b8b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f54e772b9d0>
  pre_exec: <function PreExec.pre_exec at 0x7f54e772baf0>
  pre_request: <function PreRequest.pre_request at 0x7f54e772bc10>
  post_request: <function PostRequest.post_request at 0x7f54e772bca0>
  child_exit: <function ChildExit.child_exit at 0x7f54e772bdc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f54e772bee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f54e7738040>
  on_exit: <function OnExit.on_exit at 0x7f54e7738160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 15:18:47 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 15:18:47 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 15:18:47 +0000] [7] [INFO] Listening at: http://0.0.0.0:5002 (7)
[2023-03-03 15:18:47 +0000] [7] [INFO] Using worker: sync
[2023-03-03 15:18:47 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 15:18:47 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 15:18:47 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 15:18:47 +0000] [7] [DEBUG] 3 workers
[2023-03-03 15:18:50 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 15:18:50 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-03-03 15:18:50 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 15:18:50 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-03-03 15:18:50 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 15:18:50 +0000] [11] [INFO] Worker exiting (pid: 11)
[2023-03-03 15:18:50 +0000] [7] [WARNING] Worker with pid 9 was terminated due to signal 15
[2023-03-03 15:18:50 +0000] [7] [WARNING] Worker with pid 11 was terminated due to signal 15
[2023-03-03 15:18:50 +0000] [7] [INFO] Shutting down: Master
[2023-03-03 15:18:50 +0000] [7] [INFO] Reason: Worker failed to boot.
[2023-03-03 15:53:28 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5002']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f1f588511f0>
  on_reload: <function OnReload.on_reload at 0x7f1f58851310>
  when_ready: <function WhenReady.when_ready at 0x7f1f58851430>
  pre_fork: <function Prefork.pre_fork at 0x7f1f58851550>
  post_fork: <function Postfork.post_fork at 0x7f1f58851670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f1f58851790>
  worker_int: <function WorkerInt.worker_int at 0x7f1f588518b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f1f588519d0>
  pre_exec: <function PreExec.pre_exec at 0x7f1f58851af0>
  pre_request: <function PreRequest.pre_request at 0x7f1f58851c10>
  post_request: <function PostRequest.post_request at 0x7f1f58851ca0>
  child_exit: <function ChildExit.child_exit at 0x7f1f58851dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f1f58851ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f1f5885e040>
  on_exit: <function OnExit.on_exit at 0x7f1f5885e160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 15:53:28 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 15:53:28 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 15:53:28 +0000] [7] [INFO] Listening at: http://0.0.0.0:5002 (7)
[2023-03-03 15:53:28 +0000] [7] [INFO] Using worker: sync
[2023-03-03 15:53:28 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 15:53:28 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 15:53:28 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 15:53:28 +0000] [7] [DEBUG] 3 workers
[2023-03-03 15:53:32 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 15:53:32 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 15:53:32 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-03-03 15:53:32 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-03-03 15:53:32 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 15:53:32 +0000] [11] [INFO] Worker exiting (pid: 11)
[2023-03-03 16:00:20 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5002']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7efc161f11f0>
  on_reload: <function OnReload.on_reload at 0x7efc161f1310>
  when_ready: <function WhenReady.when_ready at 0x7efc161f1430>
  pre_fork: <function Prefork.pre_fork at 0x7efc161f1550>
  post_fork: <function Postfork.post_fork at 0x7efc161f1670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7efc161f1790>
  worker_int: <function WorkerInt.worker_int at 0x7efc161f18b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7efc161f19d0>
  pre_exec: <function PreExec.pre_exec at 0x7efc161f1af0>
  pre_request: <function PreRequest.pre_request at 0x7efc161f1c10>
  post_request: <function PostRequest.post_request at 0x7efc161f1ca0>
  child_exit: <function ChildExit.child_exit at 0x7efc161f1dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7efc161f1ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7efc161ff040>
  on_exit: <function OnExit.on_exit at 0x7efc161ff160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 16:00:20 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 16:00:20 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 16:00:20 +0000] [7] [INFO] Listening at: http://0.0.0.0:5002 (7)
[2023-03-03 16:00:20 +0000] [7] [INFO] Using worker: sync
[2023-03-03 16:00:20 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 16:00:20 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 16:00:20 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 16:00:20 +0000] [7] [DEBUG] 3 workers
[2023-03-03 16:00:23 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:00:23 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:00:23 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-03-03 16:00:23 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:00:23 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-03-03 16:00:23 +0000] [11] [INFO] Worker exiting (pid: 11)
[2023-03-03 16:00:23 +0000] [7] [WARNING] Worker with pid 11 was terminated due to signal 15
[2023-03-03 16:19:29 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5002']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f6eaec701f0>
  on_reload: <function OnReload.on_reload at 0x7f6eaec70310>
  when_ready: <function WhenReady.when_ready at 0x7f6eaec70430>
  pre_fork: <function Prefork.pre_fork at 0x7f6eaec70550>
  post_fork: <function Postfork.post_fork at 0x7f6eaec70670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f6eaec70790>
  worker_int: <function WorkerInt.worker_int at 0x7f6eaec708b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f6eaec709d0>
  pre_exec: <function PreExec.pre_exec at 0x7f6eaec70af0>
  pre_request: <function PreRequest.pre_request at 0x7f6eaec70c10>
  post_request: <function PostRequest.post_request at 0x7f6eaec70ca0>
  child_exit: <function ChildExit.child_exit at 0x7f6eaec70dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f6eaec70ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f6eaec7d040>
  on_exit: <function OnExit.on_exit at 0x7f6eaec7d160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 16:19:29 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 16:19:29 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 16:19:29 +0000] [7] [INFO] Listening at: http://0.0.0.0:5002 (7)
[2023-03-03 16:19:29 +0000] [7] [INFO] Using worker: sync
[2023-03-03 16:19:29 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 16:19:29 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 16:19:29 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 16:19:29 +0000] [7] [DEBUG] 3 workers
[2023-03-03 16:19:35 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:19:35 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-03-03 16:19:35 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:19:35 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-03-03 16:19:35 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:19:35 +0000] [11] [INFO] Worker exiting (pid: 11)
[2023-03-03 16:19:51 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5002']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7ffa230e11f0>
  on_reload: <function OnReload.on_reload at 0x7ffa230e1310>
  when_ready: <function WhenReady.when_ready at 0x7ffa230e1430>
  pre_fork: <function Prefork.pre_fork at 0x7ffa230e1550>
  post_fork: <function Postfork.post_fork at 0x7ffa230e1670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7ffa230e1790>
  worker_int: <function WorkerInt.worker_int at 0x7ffa230e18b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7ffa230e19d0>
  pre_exec: <function PreExec.pre_exec at 0x7ffa230e1af0>
  pre_request: <function PreRequest.pre_request at 0x7ffa230e1c10>
  post_request: <function PostRequest.post_request at 0x7ffa230e1ca0>
  child_exit: <function ChildExit.child_exit at 0x7ffa230e1dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7ffa230e1ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7ffa230ed040>
  on_exit: <function OnExit.on_exit at 0x7ffa230ed160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 16:19:51 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 16:19:51 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 16:19:51 +0000] [7] [INFO] Listening at: http://0.0.0.0:5002 (7)
[2023-03-03 16:19:51 +0000] [7] [INFO] Using worker: sync
[2023-03-03 16:19:51 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 16:19:51 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 16:19:51 +0000] [7] [DEBUG] 3 workers
[2023-03-03 16:19:51 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 16:19:56 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:19:56 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-03-03 16:19:56 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:19:56 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-03-03 16:19:57 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:19:57 +0000] [11] [INFO] Worker exiting (pid: 11)
[2023-03-03 16:20:02 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5002']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7ff00836c1f0>
  on_reload: <function OnReload.on_reload at 0x7ff00836c310>
  when_ready: <function WhenReady.when_ready at 0x7ff00836c430>
  pre_fork: <function Prefork.pre_fork at 0x7ff00836c550>
  post_fork: <function Postfork.post_fork at 0x7ff00836c670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7ff00836c790>
  worker_int: <function WorkerInt.worker_int at 0x7ff00836c8b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7ff00836c9d0>
  pre_exec: <function PreExec.pre_exec at 0x7ff00836caf0>
  pre_request: <function PreRequest.pre_request at 0x7ff00836cc10>
  post_request: <function PostRequest.post_request at 0x7ff00836cca0>
  child_exit: <function ChildExit.child_exit at 0x7ff00836cdc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7ff00836cee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7ff008379040>
  on_exit: <function OnExit.on_exit at 0x7ff008379160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 16:20:02 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 16:20:02 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 16:20:02 +0000] [7] [INFO] Listening at: http://0.0.0.0:5002 (7)
[2023-03-03 16:20:02 +0000] [7] [INFO] Using worker: sync
[2023-03-03 16:20:02 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 16:20:02 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 16:20:02 +0000] [7] [DEBUG] 3 workers
[2023-03-03 16:20:02 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 16:20:08 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:20:08 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-03-03 16:20:08 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:20:08 +0000] [11] [INFO] Worker exiting (pid: 11)
[2023-03-03 16:20:08 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:20:08 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-03-03 16:20:16 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5002']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f8ff03b31f0>
  on_reload: <function OnReload.on_reload at 0x7f8ff03b3310>
  when_ready: <function WhenReady.when_ready at 0x7f8ff03b3430>
  pre_fork: <function Prefork.pre_fork at 0x7f8ff03b3550>
  post_fork: <function Postfork.post_fork at 0x7f8ff03b3670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f8ff03b3790>
  worker_int: <function WorkerInt.worker_int at 0x7f8ff03b38b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f8ff03b39d0>
  pre_exec: <function PreExec.pre_exec at 0x7f8ff03b3af0>
  pre_request: <function PreRequest.pre_request at 0x7f8ff03b3c10>
  post_request: <function PostRequest.post_request at 0x7f8ff03b3ca0>
  child_exit: <function ChildExit.child_exit at 0x7f8ff03b3dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f8ff03b3ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f8ff03c1040>
  on_exit: <function OnExit.on_exit at 0x7f8ff03c1160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 16:20:16 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 16:20:16 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 16:20:16 +0000] [7] [INFO] Listening at: http://0.0.0.0:5002 (7)
[2023-03-03 16:20:16 +0000] [7] [INFO] Using worker: sync
[2023-03-03 16:20:16 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 16:20:17 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 16:20:17 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 16:20:17 +0000] [7] [DEBUG] 3 workers
[2023-03-03 16:20:22 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:20:22 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-03-03 16:20:22 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:20:22 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-03-03 16:20:22 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 3, in <module>
    app = create_app()
  File "/app/flaskr/__init__.py", line 64, in create_app
    db.init_app(app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 326, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.8/dist-packages/flask_sqlalchemy/extension.py", line 614, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 605, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 667, in import_dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
[2023-03-03 16:20:22 +0000] [11] [INFO] Worker exiting (pid: 11)
[2023-03-03 16:20:23 +0000] [7] [WARNING] Worker with pid 10 was terminated due to signal 15
[2023-03-03 16:20:23 +0000] [7] [WARNING] Worker with pid 11 was terminated due to signal 15
[2023-03-03 16:20:23 +0000] [7] [INFO] Shutting down: Master
[2023-03-03 16:20:23 +0000] [7] [INFO] Reason: Worker failed to boot.
[2023-03-03 16:20:31 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5003']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f51476b11f0>
  on_reload: <function OnReload.on_reload at 0x7f51476b1310>
  when_ready: <function WhenReady.when_ready at 0x7f51476b1430>
  pre_fork: <function Prefork.pre_fork at 0x7f51476b1550>
  post_fork: <function Postfork.post_fork at 0x7f51476b1670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f51476b1790>
  worker_int: <function WorkerInt.worker_int at 0x7f51476b18b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f51476b19d0>
  pre_exec: <function PreExec.pre_exec at 0x7f51476b1af0>
  pre_request: <function PreRequest.pre_request at 0x7f51476b1c10>
  post_request: <function PostRequest.post_request at 0x7f51476b1ca0>
  child_exit: <function ChildExit.child_exit at 0x7f51476b1dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f51476b1ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f51476bd040>
  on_exit: <function OnExit.on_exit at 0x7f51476bd160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 16:20:31 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 16:20:31 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 16:20:31 +0000] [7] [INFO] Listening at: http://0.0.0.0:5003 (7)
[2023-03-03 16:20:31 +0000] [7] [INFO] Using worker: sync
[2023-03-03 16:20:31 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 16:20:31 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 16:20:31 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 16:20:31 +0000] [7] [DEBUG] 3 workers
[2023-03-03 16:20:34 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 1, in <module>
    from flaskr import create_app
  File "/app/flaskr/__init__.py", line 13, in <module>
    from grading_app.appallsub import insertSubmissionToDB
  File "/app/grading_app/appallsub.py", line 13, in <module>
    from grading_app.utils.report import report
  File "/app/grading_app/utils/report.py", line 6, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'
[2023-03-03 16:20:34 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-03-03 16:20:34 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 1, in <module>
    from flaskr import create_app
  File "/app/flaskr/__init__.py", line 13, in <module>
    from grading_app.appallsub import insertSubmissionToDB
  File "/app/grading_app/appallsub.py", line 13, in <module>
    from grading_app.utils.report import report
  File "/app/grading_app/utils/report.py", line 6, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'
[2023-03-03 16:20:34 +0000] [11] [INFO] Worker exiting (pid: 11)
[2023-03-03 16:20:34 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/wsgi.py", line 1, in <module>
    from flaskr import create_app
  File "/app/flaskr/__init__.py", line 13, in <module>
    from grading_app.appallsub import insertSubmissionToDB
  File "/app/grading_app/appallsub.py", line 13, in <module>
    from grading_app.utils.report import report
  File "/app/grading_app/utils/report.py", line 6, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'
[2023-03-03 16:20:34 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-03-03 16:20:35 +0000] [7] [WARNING] Worker with pid 10 was terminated due to signal 15
[2023-03-03 16:20:35 +0000] [7] [WARNING] Worker with pid 11 was terminated due to signal 15
[2023-03-03 16:20:35 +0000] [7] [INFO] Shutting down: Master
[2023-03-03 16:20:35 +0000] [7] [INFO] Reason: Worker failed to boot.
[2023-03-03 16:23:09 +0000] [9] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5003']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f0864c961f0>
  on_reload: <function OnReload.on_reload at 0x7f0864c96310>
  when_ready: <function WhenReady.when_ready at 0x7f0864c96430>
  pre_fork: <function Prefork.pre_fork at 0x7f0864c96550>
  post_fork: <function Postfork.post_fork at 0x7f0864c96670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f0864c96790>
  worker_int: <function WorkerInt.worker_int at 0x7f0864c968b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f0864c969d0>
  pre_exec: <function PreExec.pre_exec at 0x7f0864c96af0>
  pre_request: <function PreRequest.pre_request at 0x7f0864c96c10>
  post_request: <function PostRequest.post_request at 0x7f0864c96ca0>
  child_exit: <function ChildExit.child_exit at 0x7f0864c96dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f0864c96ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f0864ca4040>
  on_exit: <function OnExit.on_exit at 0x7f0864ca4160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 16:23:09 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2023-03-03 16:23:09 +0000] [9] [DEBUG] Arbiter booted
[2023-03-03 16:23:09 +0000] [9] [INFO] Listening at: http://0.0.0.0:5003 (9)
[2023-03-03 16:23:09 +0000] [9] [INFO] Using worker: sync
[2023-03-03 16:23:09 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 16:23:09 +0000] [12] [INFO] Booting worker with pid: 12
[2023-03-03 16:23:09 +0000] [13] [INFO] Booting worker with pid: 13
[2023-03-03 16:23:09 +0000] [9] [DEBUG] 3 workers
[2023-03-03 16:25:10 +0000] [9] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5003']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f3d6def11f0>
  on_reload: <function OnReload.on_reload at 0x7f3d6def1310>
  when_ready: <function WhenReady.when_ready at 0x7f3d6def1430>
  pre_fork: <function Prefork.pre_fork at 0x7f3d6def1550>
  post_fork: <function Postfork.post_fork at 0x7f3d6def1670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f3d6def1790>
  worker_int: <function WorkerInt.worker_int at 0x7f3d6def18b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f3d6def19d0>
  pre_exec: <function PreExec.pre_exec at 0x7f3d6def1af0>
  pre_request: <function PreRequest.pre_request at 0x7f3d6def1c10>
  post_request: <function PostRequest.post_request at 0x7f3d6def1ca0>
  child_exit: <function ChildExit.child_exit at 0x7f3d6def1dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f3d6def1ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f3d6deff040>
  on_exit: <function OnExit.on_exit at 0x7f3d6deff160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 16:25:10 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2023-03-03 16:25:10 +0000] [9] [DEBUG] Arbiter booted
[2023-03-03 16:25:10 +0000] [9] [INFO] Listening at: http://0.0.0.0:5003 (9)
[2023-03-03 16:25:10 +0000] [9] [INFO] Using worker: sync
[2023-03-03 16:25:10 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 16:25:10 +0000] [12] [INFO] Booting worker with pid: 12
[2023-03-03 16:25:10 +0000] [13] [INFO] Booting worker with pid: 13
[2023-03-03 16:25:10 +0000] [9] [DEBUG] 3 workers
[2023-03-03 16:40:00 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5003']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f34d26a61f0>
  on_reload: <function OnReload.on_reload at 0x7f34d26a6310>
  when_ready: <function WhenReady.when_ready at 0x7f34d26a6430>
  pre_fork: <function Prefork.pre_fork at 0x7f34d26a6550>
  post_fork: <function Postfork.post_fork at 0x7f34d26a6670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f34d26a6790>
  worker_int: <function WorkerInt.worker_int at 0x7f34d26a68b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f34d26a69d0>
  pre_exec: <function PreExec.pre_exec at 0x7f34d26a6af0>
  pre_request: <function PreRequest.pre_request at 0x7f34d26a6c10>
  post_request: <function PostRequest.post_request at 0x7f34d26a6ca0>
  child_exit: <function ChildExit.child_exit at 0x7f34d26a6dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f34d26a6ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f34d26b4040>
  on_exit: <function OnExit.on_exit at 0x7f34d26b4160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 16:40:00 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 16:40:00 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 16:40:00 +0000] [7] [INFO] Listening at: http://0.0.0.0:5003 (7)
[2023-03-03 16:40:00 +0000] [7] [INFO] Using worker: sync
[2023-03-03 16:40:00 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 16:40:00 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 16:40:00 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 16:40:00 +0000] [7] [DEBUG] 3 workers
[2023-03-03 16:40:17 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 16:40:59 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 16:50:05 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 16:50:06 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 16:53:08 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 16:53:53 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 16:55:23 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 16:55:52 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 16:56:21 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 16:57:02 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 16:57:07 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 16:57:28 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 17:04:26 +0000] [11] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5003']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f02f0a861f0>
  on_reload: <function OnReload.on_reload at 0x7f02f0a86310>
  when_ready: <function WhenReady.when_ready at 0x7f02f0a86430>
  pre_fork: <function Prefork.pre_fork at 0x7f02f0a86550>
  post_fork: <function Postfork.post_fork at 0x7f02f0a86670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f02f0a86790>
  worker_int: <function WorkerInt.worker_int at 0x7f02f0a868b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f02f0a869d0>
  pre_exec: <function PreExec.pre_exec at 0x7f02f0a86af0>
  pre_request: <function PreRequest.pre_request at 0x7f02f0a86c10>
  post_request: <function PostRequest.post_request at 0x7f02f0a86ca0>
  child_exit: <function ChildExit.child_exit at 0x7f02f0a86dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f02f0a86ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f02f0a94040>
  on_exit: <function OnExit.on_exit at 0x7f02f0a94160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 17:04:26 +0000] [11] [INFO] Starting gunicorn 20.1.0
[2023-03-03 17:04:26 +0000] [11] [DEBUG] Arbiter booted
[2023-03-03 17:04:26 +0000] [11] [INFO] Listening at: http://0.0.0.0:5003 (11)
[2023-03-03 17:04:26 +0000] [11] [INFO] Using worker: sync
[2023-03-03 17:04:26 +0000] [13] [INFO] Booting worker with pid: 13
[2023-03-03 17:04:26 +0000] [14] [INFO] Booting worker with pid: 14
[2023-03-03 17:04:26 +0000] [15] [INFO] Booting worker with pid: 15
[2023-03-03 17:04:26 +0000] [11] [DEBUG] 3 workers
[2023-03-03 17:04:29 +0000] [14] [DEBUG] POST /api/grader
[2023-03-03 17:07:08 +0000] [14] [DEBUG] POST /api/grader
[2023-03-03 17:20:42 +0000] [8] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5003']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fe906a4d1f0>
  on_reload: <function OnReload.on_reload at 0x7fe906a4d310>
  when_ready: <function WhenReady.when_ready at 0x7fe906a4d430>
  pre_fork: <function Prefork.pre_fork at 0x7fe906a4d550>
  post_fork: <function Postfork.post_fork at 0x7fe906a4d670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fe906a4d790>
  worker_int: <function WorkerInt.worker_int at 0x7fe906a4d8b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fe906a4d9d0>
  pre_exec: <function PreExec.pre_exec at 0x7fe906a4daf0>
  pre_request: <function PreRequest.pre_request at 0x7fe906a4dc10>
  post_request: <function PostRequest.post_request at 0x7fe906a4dca0>
  child_exit: <function ChildExit.child_exit at 0x7fe906a4ddc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7fe906a4dee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fe906a5b040>
  on_exit: <function OnExit.on_exit at 0x7fe906a5b160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 17:20:42 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2023-03-03 17:20:42 +0000] [8] [DEBUG] Arbiter booted
[2023-03-03 17:20:42 +0000] [8] [INFO] Listening at: http://0.0.0.0:5003 (8)
[2023-03-03 17:20:42 +0000] [8] [INFO] Using worker: sync
[2023-03-03 17:20:42 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 17:20:42 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 17:20:42 +0000] [12] [INFO] Booting worker with pid: 12
[2023-03-03 17:20:42 +0000] [8] [DEBUG] 3 workers
[2023-03-03 17:22:33 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5003']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f593f6b81f0>
  on_reload: <function OnReload.on_reload at 0x7f593f6b8310>
  when_ready: <function WhenReady.when_ready at 0x7f593f6b8430>
  pre_fork: <function Prefork.pre_fork at 0x7f593f6b8550>
  post_fork: <function Postfork.post_fork at 0x7f593f6b8670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f593f6b8790>
  worker_int: <function WorkerInt.worker_int at 0x7f593f6b88b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f593f6b89d0>
  pre_exec: <function PreExec.pre_exec at 0x7f593f6b8af0>
  pre_request: <function PreRequest.pre_request at 0x7f593f6b8c10>
  post_request: <function PostRequest.post_request at 0x7f593f6b8ca0>
  child_exit: <function ChildExit.child_exit at 0x7f593f6b8dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f593f6b8ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f593f6c6040>
  on_exit: <function OnExit.on_exit at 0x7f593f6c6160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 17:22:33 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 17:22:33 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 17:22:33 +0000] [7] [INFO] Listening at: http://0.0.0.0:5003 (7)
[2023-03-03 17:22:33 +0000] [7] [INFO] Using worker: sync
[2023-03-03 17:22:33 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 17:22:33 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 17:22:33 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 17:22:33 +0000] [7] [DEBUG] 3 workers
[2023-03-03 17:22:47 +0000] [8] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5003']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f1c2379a1f0>
  on_reload: <function OnReload.on_reload at 0x7f1c2379a310>
  when_ready: <function WhenReady.when_ready at 0x7f1c2379a430>
  pre_fork: <function Prefork.pre_fork at 0x7f1c2379a550>
  post_fork: <function Postfork.post_fork at 0x7f1c2379a670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f1c2379a790>
  worker_int: <function WorkerInt.worker_int at 0x7f1c2379a8b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f1c2379a9d0>
  pre_exec: <function PreExec.pre_exec at 0x7f1c2379aaf0>
  pre_request: <function PreRequest.pre_request at 0x7f1c2379ac10>
  post_request: <function PostRequest.post_request at 0x7f1c2379aca0>
  child_exit: <function ChildExit.child_exit at 0x7f1c2379adc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f1c2379aee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f1c237a8040>
  on_exit: <function OnExit.on_exit at 0x7f1c237a8160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 17:22:47 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2023-03-03 17:22:47 +0000] [8] [DEBUG] Arbiter booted
[2023-03-03 17:22:47 +0000] [8] [INFO] Listening at: http://0.0.0.0:5003 (8)
[2023-03-03 17:22:47 +0000] [8] [INFO] Using worker: sync
[2023-03-03 17:22:47 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 17:22:47 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 17:22:47 +0000] [12] [INFO] Booting worker with pid: 12
[2023-03-03 17:22:47 +0000] [8] [DEBUG] 3 workers
[2023-03-03 17:25:31 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5003']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f0ec93871f0>
  on_reload: <function OnReload.on_reload at 0x7f0ec9387310>
  when_ready: <function WhenReady.when_ready at 0x7f0ec9387430>
  pre_fork: <function Prefork.pre_fork at 0x7f0ec9387550>
  post_fork: <function Postfork.post_fork at 0x7f0ec9387670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f0ec9387790>
  worker_int: <function WorkerInt.worker_int at 0x7f0ec93878b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f0ec93879d0>
  pre_exec: <function PreExec.pre_exec at 0x7f0ec9387af0>
  pre_request: <function PreRequest.pre_request at 0x7f0ec9387c10>
  post_request: <function PostRequest.post_request at 0x7f0ec9387ca0>
  child_exit: <function ChildExit.child_exit at 0x7f0ec9387dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f0ec9387ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f0ec9395040>
  on_exit: <function OnExit.on_exit at 0x7f0ec9395160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 17:25:31 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 17:25:31 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 17:25:31 +0000] [7] [INFO] Listening at: http://0.0.0.0:5003 (7)
[2023-03-03 17:25:31 +0000] [7] [INFO] Using worker: sync
[2023-03-03 17:25:31 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 17:25:31 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 17:25:32 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 17:25:32 +0000] [7] [DEBUG] 3 workers
[2023-03-03 17:25:45 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 17:29:02 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5003']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f647bc4c1f0>
  on_reload: <function OnReload.on_reload at 0x7f647bc4c310>
  when_ready: <function WhenReady.when_ready at 0x7f647bc4c430>
  pre_fork: <function Prefork.pre_fork at 0x7f647bc4c550>
  post_fork: <function Postfork.post_fork at 0x7f647bc4c670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f647bc4c790>
  worker_int: <function WorkerInt.worker_int at 0x7f647bc4c8b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f647bc4c9d0>
  pre_exec: <function PreExec.pre_exec at 0x7f647bc4caf0>
  pre_request: <function PreRequest.pre_request at 0x7f647bc4cc10>
  post_request: <function PostRequest.post_request at 0x7f647bc4cca0>
  child_exit: <function ChildExit.child_exit at 0x7f647bc4cdc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f647bc4cee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f647bc5a040>
  on_exit: <function OnExit.on_exit at 0x7f647bc5a160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 17:29:02 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 17:29:02 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 17:29:02 +0000] [7] [INFO] Listening at: http://0.0.0.0:5003 (7)
[2023-03-03 17:29:02 +0000] [7] [INFO] Using worker: sync
[2023-03-03 17:29:02 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 17:29:02 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 17:29:02 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 17:29:03 +0000] [7] [DEBUG] 3 workers
[2023-03-03 17:29:07 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 17:42:45 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 17:45:16 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 17:49:56 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 17:56:11 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 17:58:01 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 18:00:04 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 18:01:37 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 18:04:22 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:05:26 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 18:06:46 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:08:49 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:09:38 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:11:43 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 18:12:26 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 18:14:36 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 18:16:56 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:17:16 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 18:18:40 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 18:18:47 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 18:22:54 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 18:26:29 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 18:26:39 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:27:45 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:28:13 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:29:22 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:30:48 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:35:20 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:43:25 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 18:45:25 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:51:29 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 18:52:47 +0000] [7] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5003']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /app
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/03-03-2023.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fabb5a151f0>
  on_reload: <function OnReload.on_reload at 0x7fabb5a15310>
  when_ready: <function WhenReady.when_ready at 0x7fabb5a15430>
  pre_fork: <function Prefork.pre_fork at 0x7fabb5a15550>
  post_fork: <function Postfork.post_fork at 0x7fabb5a15670>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fabb5a15790>
  worker_int: <function WorkerInt.worker_int at 0x7fabb5a158b0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fabb5a159d0>
  pre_exec: <function PreExec.pre_exec at 0x7fabb5a15af0>
  pre_request: <function PreRequest.pre_request at 0x7fabb5a15c10>
  post_request: <function PostRequest.post_request at 0x7fabb5a15ca0>
  child_exit: <function ChildExit.child_exit at 0x7fabb5a15dc0>
  worker_exit: <function WorkerExit.worker_exit at 0x7fabb5a15ee0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fabb5a23040>
  on_exit: <function OnExit.on_exit at 0x7fabb5a23160>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-03-03 18:52:47 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-03-03 18:52:47 +0000] [7] [DEBUG] Arbiter booted
[2023-03-03 18:52:47 +0000] [7] [INFO] Listening at: http://0.0.0.0:5003 (7)
[2023-03-03 18:52:47 +0000] [7] [INFO] Using worker: sync
[2023-03-03 18:52:47 +0000] [9] [INFO] Booting worker with pid: 9
[2023-03-03 18:52:47 +0000] [10] [INFO] Booting worker with pid: 10
[2023-03-03 18:52:47 +0000] [11] [INFO] Booting worker with pid: 11
[2023-03-03 18:52:47 +0000] [7] [DEBUG] 3 workers
[2023-03-03 18:53:14 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 18:57:08 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 18:58:45 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 19:00:16 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 19:01:46 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 19:09:33 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 19:11:39 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 19:17:07 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 19:24:13 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 19:26:33 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 19:28:42 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 19:31:58 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 19:40:55 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 19:46:44 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 19:48:15 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 19:49:41 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 19:57:38 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 20:01:37 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 20:07:01 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 20:08:44 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 20:10:52 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 20:16:29 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 20:19:11 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 20:20:01 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 20:21:06 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 20:21:18 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 20:28:44 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 20:31:25 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 21:33:47 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 21:59:16 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 22:03:35 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 22:04:41 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 22:05:17 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 22:06:53 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 22:28:42 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 23:05:49 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 23:07:27 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 23:13:29 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 23:17:12 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 23:19:03 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 23:21:05 +0000] [9] [DEBUG] POST /api/grader
[2023-03-03 23:23:34 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 23:27:41 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 23:30:10 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 23:30:45 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 23:39:49 +0000] [11] [DEBUG] POST /api/grader
[2023-03-03 23:40:24 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 23:41:35 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 23:48:01 +0000] [10] [DEBUG] POST /api/grader
[2023-03-03 23:54:18 +0000] [10] [DEBUG] POST /api/grader
[2023-03-04 00:01:02 +0000] [10] [DEBUG] POST /api/grader
[2023-03-04 00:02:34 +0000] [10] [DEBUG] POST /api/grader
[2023-03-04 00:05:12 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 00:07:52 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 00:12:06 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 00:15:31 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 00:22:15 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 00:23:00 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 00:23:49 +0000] [10] [DEBUG] POST /api/grader
[2023-03-04 00:25:57 +0000] [10] [DEBUG] POST /api/grader
[2023-03-04 00:28:05 +0000] [10] [DEBUG] POST /api/grader
[2023-03-04 00:31:12 +0000] [10] [DEBUG] POST /api/grader
[2023-03-04 00:31:52 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 00:34:35 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 00:35:30 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:10)
[2023-03-04 00:35:30 +0000] [10] [INFO] Worker exiting (pid: 10)
[2023-03-04 00:35:31 +0000] [8460] [INFO] Booting worker with pid: 8460
[2023-03-04 00:35:44 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 00:35:54 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 00:36:27 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 00:37:50 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 00:40:06 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 00:45:42 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 00:48:05 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 00:48:21 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 00:48:56 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 00:49:18 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 00:49:21 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 00:50:58 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 00:51:24 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 00:52:05 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 00:53:08 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 00:54:57 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 00:56:33 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 00:57:22 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 00:58:46 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 00:59:35 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 00:59:44 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 00:59:57 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:01:52 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:03:08 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:03:13 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:03:25 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:03:45 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:05:14 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:05:31 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:06:02 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:06:07 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:06:35 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:08:40 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:08:50 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:09:05 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:09:52 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:10:03 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:10:22 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:10:45 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:10:54 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:11:00 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:11:25 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:15:18 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:16:13 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:16:42 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:17:15 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:17:23 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:17:58 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:18:06 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:18:23 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:18:23 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:18:56 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:19:39 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:20:24 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:20:42 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:20:47 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:21:02 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:21:16 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:22:25 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:23:48 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:24:50 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:24:58 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:25:03 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:27:40 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:28:35 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:29:07 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:29:49 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:30:07 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:30:39 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:30:52 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:31:32 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:31:37 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:31:45 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:31:58 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:33:04 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:33:12 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:33:56 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:34:11 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:35:14 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:35:18 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:35:43 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:36:14 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:36:38 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:36:47 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:37:39 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:37:50 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:38:21 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:38:25 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:39:48 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:39:51 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:40:22 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:41:47 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:44:56 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:45:31 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:45:36 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:45:47 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:46:23 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:47:08 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:47:56 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:48:41 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:49:07 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:49:13 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:49:19 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:49:23 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:49:34 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:49:43 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:49:56 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:49:57 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:50:05 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:50:56 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:52:30 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:52:31 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:52:45 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:52:48 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:52:51 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:53:09 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:53:21 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:53:22 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:54:07 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:54:16 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:54:25 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:54:27 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:55:03 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:55:04 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:55:12 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:55:53 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:56:07 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:56:09 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:57:03 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:57:08 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:57:19 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 01:57:28 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:57:45 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:58:14 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 01:58:17 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:58:47 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 01:58:48 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 02:01:32 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 02:01:36 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 02:01:44 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 02:02:08 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 02:02:10 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 02:02:45 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 02:03:05 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 02:03:58 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 02:04:28 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 02:04:28 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 02:04:46 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 02:05:16 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 02:05:51 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 02:06:32 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 02:06:44 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 02:06:49 +0000] [11] [DEBUG] POST /api/grader
[2023-03-04 02:06:52 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 02:07:07 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 02:07:15 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 02:07:16 +0000] [8460] [DEBUG] POST /api/grader
[2023-03-04 02:07:22 +0000] [9] [DEBUG] POST /api/grader
[2023-03-04 02:07:46 +0000] [9] [DEBUG] POST /api/grader
